server {
    listen       80;
    listen       [::]:80;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    # Serve static files directly
    location / {
        try_files $uri /index.html;
    }

    # Gzip for better performance
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 256;
}


