export const classification = {
  "": [""],
  "Natural sciences": ["Mathematics and statistics", "Computer and information sciences", "Physical sciences", "Chemical sciences", "Earth and related environmental sciences", "Biological sciences", "Other natural sciences"],
  "Engineering and technology": ["Civil engineering, maritime engineering, transport engineering, and mining engineering", "Industrial, systems and processes engineering", "Electrical engineering, computer engineering, and information engineering", "Mechanical engineering", "Chemical engineering", "Materials engineering and resources engineering", "Medical and biomedical engineering", "Environmental engineering and related engineering", "Environmental biotechnology", "Industrial biotechnology", "Nano-technology", "Other engineering and technologies"],
  "Medical and health sciences": ["Basic medicine and life sciences", "Clinical medicine", "Health sciences", "Medical biotechnology", "Other medical sciences"],
  "Agricultural and veterinary sciences": ["Agriculture, forestry, and fisheries", "Animal and dairy science", "Veterinary science", "Agricultural biotechnology and food sciences", "Other agricultural sciences"],
  "Social sciences": ["Psychology and cognitive sciences", "Economics and business administration", "Education", "Sociology and related studies", "Law and legal practice", "Political science and policy administration", "Social and economic geography", "Media and communications", "Other social sciences"],
  "Humanities and the arts": ["History, archaeology and related studies", "Languages and literature", "Philosophy", "Arts (arts, history of arts, performing arts, music), architecture and design", "Other humanities"],
};

export const divisionCodes = {
  "": "",
  "Natural sciences": "RDF10",
  "Engineering and technology": "RDF20-21",
  "Medical and health sciences": "RDF30",
  "Agricultural and veterinary sciences": "RDF40",
  "Social sciences": "RDF50",
  "Humanities and the arts": "RDF60",
};

export const groupCodes = {
  "": "",
  "Mathematics and statistics": "RDF101",
  "Computer and information sciences": "RDF102",
  "Physical sciences": "RDF103",
  "Chemical sciences": "RDF104",
  "Earth and related environmental sciences": "RDF105",
  "Biological sciences": "RDF106",
  "Other natural sciences": "RDF107",
  "Civil engineering, maritime engineering, transport engineering, and mining engineering": "RDF201",
  "Industrial, systems and processes engineering": "RDF202",
  "Electrical engineering, computer engineering, and information engineering": "RDF203",
  "Mechanical engineering": "RDF204",
  "Chemical engineering": "RDF205",
  "Materials engineering and resources engineering": "RDF206",
  "Medical and biomedical engineering": "RDF207",
  "Environmental engineering and related engineering": "RDF208",
  "Environmental biotechnology": "RDF209",
  "Industrial biotechnology": "RDF210",
  "Nano-technology": "RDF211",
  "Other engineering and technologies": "RDF212",
  "Basic medicine and life sciences": "RDF301",
  "Clinical medicine": "RDF302",
  "Health sciences": "RDF303",
  "Medical biotechnology": "RDF304",
  "Other medical sciences": "RDF305",
  "Agriculture, forestry, and fisheries": "RDF401",
  "Animal and dairy science": "RDF402",
  "Veterinary science": "RDF403",
  "Agricultural biotechnology and food sciences": "RDF404",
  "Other agricultural sciences": "RDF405",
  "Psychology and cognitive sciences": "RDF501",
  "Economics and business administration": "RDF502",
  "Education": "RDF503",
  "Sociology and related studies": "RDF504",
  "Law and legal practice": "RDF505",
  "Political science and policy administration": "RDF506",
  "Social and economic geography": "RDF507",
  "Media and communications": "RDF508",
  "Other social sciences": "RDF509",
  "History, archaeology and related studies": "RDF601",
  "Languages and literature": "RDF602",
  "Philosophy": "RDF603",
  "Arts (arts, history of arts, performing arts, music), architecture and design": "RDF604",
  "Other humanities": "RDF605",
};