export const languageCodesObject = {
  afar: "aa",
  abkhazian: "ab",
  afrikaans: "af",
  akan: "ak",
  albanian: "sq",
  amharic: "am",
  arabic: "ar",
  aragonese: "an",
  armenian: "hy",
  assamese: "as",
  avaric: "av",
  avestan: "ae",
  aymara: "ay",
  azerbaijani: "az",
  bambara: "bm",
  bashkir: "ba",
  basque: "eu",
  belarusian: "be",
  bengali: "bn",
  bislama: "bi",
  bosnian: "bs",
  breton: "br",
  bulgarian: "bg",
  burmese: "my",
  catalan: "ca",
  valencian: "ca",
  chamorro: "ch",
  chechen: "ce",
  chichewa: "ny",
  chewa: "ny",
  nyanja: "ny",
  chinese: "zh",
  mandarin: "zh",
  "church slavonic": "cu",
  "old slavonic": "cu",
  "old church slavonic": "cu",
  slavonic: "cu",
  chuvash: "cv",
  cornish: "kw",
  corsican: "co",
  cree: "cr",
  croatian: "hr",
  czech: "cs",
  danish: "da",
  divehi: "dv",
  dhivehi: "dv",
  maldivian: "dv",
  dutch: "nl",
  flemish: "nl",
  dzongkha: "dz",
  english: "en",
  esperanto: "eo",
  estonian: "et",
  ewe: "ee",
  faroese: "fo",
  fijian: "fj",
  finnish: "fi",
  french: "fr",
  "western frisian": "fy",
  frisian: "fy",
  fulah: "ff",
  gaelic: "gd",
  "scottish gaelic": "gd",
  galician: "gl",
  ganda: "lg",
  georgian: "ka",
  german: "de",
  greek: "el",
  kalaallisut: "kl",
  greenlandic: "kl",
  guarani: "gn",
  gujarati: "gu",
  haitian: "ht",
  "haitian creole": "ht",
  creole: "ht",
  hausa: "ha",
  hebrew: "he",
  herero: "hz",
  hindi: "hi",
  "hiri motu": "ho",
  hungarian: "hu",
  icelandic: "is",
  ido: "io",
  igbo: "ig",
  indonesian: "id",
  interlingua: "ia",
  "international auxiliary language association": "ia",
  interlingue: "ie",
  occidental: "ie",
  inuktitut: "iu",
  inupiaq: "ik",
  irish: "ga",
  italian: "it",
  japanese: "ja",
  javanese: "jv",
  kannada: "kn",
  kanuri: "kr",
  kashmiri: "ks",
  kazakh: "kk",
  "central khmer": "km",
  khmer: "km",
  kikuyu: "ko",
  gikuyu: "ki",
  kinyarwanda: "rw",
  kirghiz: "ky",
  kyrgyz: "ky",
  komi: "kv",
  kongo: "kg",
  korean: "ko",
  kuanyama: "kj",
  kurdish: "ku",
  lao: "lo",
  latin: "la",
  latvian: "lv",
  limburgan: "li",
  limburger: "li",
  limburgish: "li",
  lingala: "ln",
  lithuanian: "lt",
  "luba-katanga": "lu",
  "luba katanga": "lu",
  luxembourgish: "lb",
  letzeburgesch: "lb",
  macedonian: "mk",
  malagasy: "mg",
  malay: "ms",
  malayalam: "ml",
  maltese: "mt",
  manx: "gv",
  maori: "mi",
  marathi: "mr",
  marshallese: "mh",
  mongolian: "mn",
  nauru: "na",
  navajo: "nv",
  navaho: "nv",
  "north ndebele": "nd",
  "south ndebele": "nr",
  ndonga: "ng",
  nepali: "ne",
  norwegian: "no",
  "norwegian bokmål": "nb",
  bokmål: "nb",
  "norwegian bokmal": "nb",
  bokmal: "nb",
  "norwegian nynorsk": "nn",
  nynorsk: "nn",
  "sichuan yi": "ii",
  nuosu: "ii",
  occitan: "oc",
  ojibwa: "oj",
  oriya: "or",
  oromo: "om",
  ossetian: "os",
  ossetic: "os",
  pali: "pi",
  pashto: "ps",
  pushto: "ps",
  persian: "fa",
  polish: "pl",
  portuguese: "pt",
  punjabi: "pa",
  panjabi: "pa",
  quechua: "qu",
  romanian: "ro",
  moldavian: "ro",
  moldovan: "ro",
  romansh: "rm",
  rundi: "rn",
  russian: "ru",
  "northern sami": "se",
  sami: "se",
  samoan: "sm",
  sango: "sg",
  sanskrit: "sa",
  sardinian: "sc",
  serbian: "sr",
  shona: "sn",
  sindhi: "sd",
  sinhala: "si",
  sinhalese: "si",
  slovak: "sk",
  slovenian: "sl",
  somali: "so",
  "southern sotho": "st",
  sotho: "st",
  spanish: "es",
  castilian: "es",
  sundanese: "su",
  swahili: "sw",
  swati: "ss",
  swedish: "sv",
  tagalog: "tl",
  tahitian: "ty",
  tajik: "tg",
  tamil: "ta",
  tatar: "tt",
  telugu: "te",
  thai: "th",
  tibetan: "bo",
  tigrinya: "ti",
  tonga: "to",
  "tonga islands": "to",
  tsonga: "ts",
  tswana: "tn",
  turkish: "tr",
  turkmen: "tk",
  twi: "tw",
  uighur: "ug",
  uyghur: "ug",
  ukrainian: "uk",
  urdu: "ur",
  uzbek: "uz",
  venda: "ve",
  vietnamese: "vi",
  volapük: "vo",
  volapuk: "vo",
  walloon: "wa",
  welsh: "cy",
  wolof: "wo",
  xhosa: "xh",
  yiddish: "yi",
  yoruba: "yo",
  zhuang: "za",
  chuang: "za",
  zulu: "zu",
};

export const codesToLanguages = {
  en: "English",
  fr: "French",
  es: "Spanish",
  zh: "Mandarin",
  de: "German",
  ja: "Japanese",
  it: "Italian"
};

export const allLanguagesWithCodesArray = Object.keys(languageCodesObject);
